### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by martinwguy** [Tux/VCS-SCCS#2]
Er... OK, so I cloned the repo and made install. I have an (old!) SCCS repo and want to do something useful with it. How do I invoke this tool? Maybe some extra lines in README?

Thanks, hoping well!

    M

**Comment by Tux** [comment]
Hmm, the docs are not complete, but they are reallysufficient to start, so, did you read them?
```
$ perldoc VCS::SCCS
NAME
    VCS::SCCS - OO Interface to SCCS files

SYNOPSIS
     use VCS::SCCS;

     my $sccs = VCS::SCCS->new ("SCCS/s.file.pl");   # Read and parse

     # Meta info
     my $fn = $sccs->file ();            # file.pl
     my $cs = $sccs->checksum ();        # 52534
     my @us = $sccs->users ();           # qw( merijn user )
     my $fl = $sccs->flags ();           # { q => "Test applic", v => undef }
     my $cm = $sccs->comment ();         # ""
     my $cr = $sccs->current ();         # 70
     my @cr = $sccs->current ();         # ( 70, "5.39", 5, 39 )

     # Delta related
     my $vs = $sccs->version ();         # "5.39"
     my $vs = $sccs->version (69);       # "5.38"
     my $rv = $sccs->revision ();        # 70
     my $rv = $sccs->revision ("5.37");  # 68
     my $rm = $sccs->revision_map ();    # [ [ 1, "4.1" ], ... [ 70, "5.39" ]]
     my $dd = $sccs->delta (17);         # none, revision or version as arg

     # Content related
     my $body_70 = $sccs->body ();       # file.pl @70 incl NL's
     my @body_70 = $sccs->body ();       # file.pl @70 list of chomped lines
     my @body_69 = $sccs->body (69);     # same for file.pl @96
     my @body_69 = $sccs->body ("5.38"); # same
:
:
```
And then of course there are the tools that should give you the full usage for translating SCCS to git.
https://github.com/Tux/VCS-SCCS/tree/master/examples

**Comment by martinwguy** [comment]
Thanks. Perl is not one of the 20 or 30 languages I program in, so I'd never have guessed the perldoc command. I've now installed it, and the command you gave does present the above documentation.

What I was looking for was to convert an SCCS repository to a git one, hoping to save the modification history, or to a CVS one (and thence to git), having been directed here from a web search for that, but I seem to be in the wrong place.

So let me share with you my "user experience" :)

First, I looked at the README, as is the convention, but it's unclear what this is or what it does. From your reply, it appears to be a perl library of functions for reading SCCS files.

I looked at doc/ - a copy of the manual page for the format of SCCS files. Hum.

Maybe one of the examples will do something like that? Who knows?
Let's have a look: sccs2git-add  sccs2git-gfi  sccs2git-r
-add? -gfi? -r? I wonder what they do and how to use them, but there's not a single useful comment at the top of the first two;  dives straight into Perl without giving a clue as to what the file is. 
Only one of them (-r) has a comment at the top, hinting at what it does:
```
# This is the recursive version of sccs2git
# Combining all SCCS repos to one single git repo
```
Well, I don't want to combine multiple SCCS repos into one. Maybe I can use it to "combine" a single repo, but there's no clue how to invoke it or its options, if it has any. However, it mentions sccs2git.
```
$ sccs2git
sccs2git: command not found
$
```
Maybe it's in there somewhere.
```
$ find . -name sccs2git\*
./examples/sccs2git-add
./examples/sccs2git-gfi
./examples/sccs2git-r
```
And I'm going round in circles. At this point I seek help (hi!) or look elsewhere, but actually I wanted to get working on the program under SCCS, not learn Perl enough to decipher other people's uncommented Perl code, hoping to figure it out and not destroy the SCCS repo in my attempts to do so. I'm not sure I want to do that...

So anyway, as regards VCS-SCCS, I'd suggest adding some lines at the top of README saying what VCS-SCCS is and what it does. Then how you use it, or a mention of the perldoc command you mention.

As for the examples, similarly, if they *are* tools to convert SCCS repositories to git ones, they need documenting at the top. Assume the user has no perl experience but can manage the command line.

In fact, as a professional programmer since 1985 (when I would naughtily edit SCCS files by hand to do things that you can now do with git), I'd suggest to all programmers everywhere to include a comment always at the top of every file they ever write, saying what the file is, what it does and how to use it, but I realise that young programmers tend to write for the computer, not for the people who will read their code, and assume that if they understand their own code at the time they write it, so magically will everyone else who looks at it, and that so will they, when they come back to their own code five years later.

Or maybe I *am* in the wrong place, who knows? It all looks so promising...

**Comment by Tux** [comment]
Thanks for all the feedback. I will have to sort this out before I can give you a more detailed answer if below is not sufficient. `SCCS` is a fading VCS, and after I converted all my `SCCS` repositories to `git`, I lost interest.
Perl modules are usually installed using the `cpan` command or - if available - from system packages (if your distribution includes the module in its package repository).
```
$ cpan VCS::SCCS
```
When that succeeds, the docs are available either using `perldoc` or - when available - `man`
```
$ perldoc VCS::SCCS
$ man VCS::SCCS
```
The comment `# This is the recursive version of sccs2git` is what it is: a comment. When I used this to convert all my own `SCCS` repositories to `git`, I started with a script that was able to convert a single SCCS folder. As SCCS did not support directory-trees, this was useful for a small project that only spans a single folder, but kind of useless when converting a bigger project with a complete folder tree with lots of SCCS sub-folders for each.
The `sccs2git-r` is a rewrite of my original script `sccs2git` and thereby making the original script obsolete. Doing a recursive conversion on a single folder with no subfolders is ok.
Then for the unclearity of the three scripts. They are left in place in examples because they were useful to me or the guy I worked with to make it all do what I wanted. The fact that it is not documented anywhere is a weakness (or a bug if you like).
In the end, you only need `sccs2git-r`.
```
$ cd /my/src/project/
$ perl /path/to/VSC-SCCS/examples/sccs2git-r
$ git status
```
And then check if the result is what you expected.
As using this is a one-time action (once converted, you don't need it ever more), there is close to no reason to install the scripts for later use. At least that was my opinion when I uploaded this to CPAN.
I also did a lot of manual editing in those SCCS source files. We are wicked.
I will
• Add a few lines in README
• Add a usage message in sccs2git-r

**Comment by Tux** [comment]
Done. What do you think of https://github.com/Tux/VCS-SCCS/commit/9ff9ad0ec834d980fcfdb20fbd70e1f9f2742805 ?

**Comment by martinwguy** [comment]
Perfect, exactly what I needed, many thanks.

It worked like a dream, only compaining that
```
error: The following untracked working tree files would be overwritten by checkout:
	Makefile
	rat.1
	rat.c
Please move or remove them before you switch branches.
Aborting
```
and
```
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitignore
```
but everything looks fine.

Yes, SCCS is horrid, but it's all there was at the time, so it comes back to haunt me when I think of breathing life back into some of our old crap.

> I also did a lot of manual editing in those SCCS source files. We are wicked.

And I never broke a single one! I can't believe it now, but my boss never found out :)

Blessings

    M

**Comment by martinwguy** [comment]
Oops

**Comment by martinwguy** [comment]
One more thought: you could probably rename sccs2git-r to sccs2git, as it does what sccs2git did. Or give it a -r option to descend into multiple SCCS dirs.

If sccs2git were then installed in /usr/[local/]bin, we'd be home and dry, and users wouldn't even have to know that it's written in Perl :)

Fab tool. Thanks again for publishing it.

**Comment by Tux** [comment]
I also added the documentation to the static doc/ folder. Is this a state you think viable for a new release or can I help by changing still more
I'm happy that my work helped you, and - again - I sincerely value your feedback.
I do not know what to do about those git warnings. When I converted my repo's, I most likely used an old git-1.7.x or something ancient, compiled on HP-UX. Now that the current stable is 2.26.2 (please update your git if you dd not read the CVE's yet *) things might have changed.
I know your (first) language is not perl, but "patches welcome" still stands.
https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.17.5.txt
which resulted in 2.21.3, 2.22.4, 2.23.3, 2.24.3, 2.25.4, 2.26.2 being released

**Comment by Tux** [comment]
I'll consider a rename and adding an option, but then I would make the option '--no-recurse' to disable the default recursion option.

**Comment by Tux** [comment]
Now done. Worth a release?

**Comment by martinwguy** [comment]
Sounds good.  After all, *not* wanting to convert every sub-SCCS tree is probably a rare thing to want to do. Thanks again

**Comment by Tux** [comment]
Uploaded to CPAN.
Get it from https://tux.nl/Files/VCS-SCCS-0.26.tgz if your CPAN mirror is slow.
I'm closing this issue.

**Comment by martinwguy** [comment]
OK, thanks for everything.  Good work!

   M
